// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ChakraProvider, /* extendTheme */ } from "@chakra-ui/react";
import "./globals.css";
import { UserProvider } from "@/context/context";
//import BackButtonHandler from "@/components/BackButtonHandler";

// Import your local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Extend Chakra UI theme with custom breakpoints and fonts
/* const theme = extendTheme({
  fonts: {
    body: "InterVariable, sans-serif",
    heading: "InterVariable, sans-serif",
  },
  breakpoints: {
    sm: "390px",
    md: "768px",
    lg: "992px",
    xl: "1280px",
    "2xl": "1536px",
  },
}); */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ChakraProvider /* theme={theme} */>
          <UserProvider>
            {/* <BackButtonHandler /> */}
            {children}
          </UserProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
